const res = {
  records: [
    {
      id: "1694643408660262913",
      title: "123123",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899467177299970",
      publisherName: "总经办",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-24 17:30:48",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>123123</p>",
      weight: 0,
      remarks: "",
      coverImageUrl: "",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1694176749120778241",
      title: "小视频showFlag测试",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899467177299970",
      publisherName: "总经办",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-23 10:36:28",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1694176749691203585",
          contentId: "1694176749120778241",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "0a1b1f18cba3dbd90bd348e75a1746f2",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1694168121120485378",
      title: "fsdsdf",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899467177299970",
      publisherName: "总经办",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-23 10:02:11",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1694168433692602369",
          contentId: "1694168121120485378",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "63d7a811b5ae03b621c42d890549a87e",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1693898181519409153",
      title: "sdfs",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899467177299970",
      publisherName: "总经办",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-22 16:09:32",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>sdfsdf</p>",
      weight: 0,
      remarks: "",
      coverImageUrl: "",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1693895898291306498",
      title: "dfgdfg",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899525775921153",
      publisherName: "软件研发中心",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-22 16:00:28",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1693896041858138114",
          contentId: "1693895898291306498",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "a3b95a0953df0e1d18243639ec38a9f4",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1693892487047086081",
      title: "dfgdfg",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899525775921153",
      publisherName: "软件研发中心",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-22 15:46:55",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1693892487856586754",
          contentId: "1693892487047086081",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "42ec346e3f968d4ca342beeb689326ab",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1693826195636158466",
      title: "驱蚊器",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899467177299970",
      publisherName: "总经办",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-22 11:23:29",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1693826196512768002",
          contentId: "1693826195636158466",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "d704e75c366bf25a8ce591f00ac2a343",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691396054661296130",
      title: "视频新闻001",
      status: 0,
      statusTxt: "上架",
      publisherId: "1690899525775921153",
      publisherName: "软件研发中心",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 18:26:59",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1693831415158079490",
          contentId: "1691396054661296130",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "9154508be25d5625161c2aed4e385840",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691395781964427266",
      title: "图文新闻001",
      status: 0,
      statusTxt: "上架",
      publisherId: "22",
      publisherName: "2-2-二级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 18:25:54",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText:
        '<p>史蒂夫斯地方</p><p><img src="/gok/portal/sys-file/test-portal/a7fe9c89789840c98ad1fa4353e32474.png" alt="" data-href="" style=""/></p>',
      weight: 0,
      remarks: "",
      coverImageUrl:
        "http://test-portal-obs.goktech.cn/0e07053f96c94c87a27a7fd149a54391.png?x-image-process=style/148_104",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1691394078464634882",
      title: "h5链接封面",
      status: 0,
      statusTxt: "上架",
      publisherId: "22",
      publisherName: "2-2-二级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 18:19:08",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 1,
      contentTypeTxt: "H5链接",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: "http://www.goktech.cn",
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl:
        "http://test-portal-obs.goktech.cn/367961b1d26c4c1284af943cb08bad61.jpeg?x-image-process=style/148_104",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1691123183296569345",
      title: "5",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 00:22:41",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691123184215121922",
          contentId: "1691123183296569345",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "bd488bb595408eef97c62dad0e3f9389",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691121463615152129",
      title: "44",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 00:15:51",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691121464537899009",
          contentId: "1691121463615152129",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "5b3d6073aa9f8f0629601c9019ac547f",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691119663713476609",
      title: "4",
      status: 0,
      statusTxt: "上架",
      publisherId: "2",
      publisherName: "2-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 00:08:42",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1691119614317158401",
      title: "4",
      status: 0,
      statusTxt: "上架",
      publisherId: "2",
      publisherName: "2-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-15 00:08:30",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1691114590576959490",
      title: "3视频",
      status: 0,
      statusTxt: "上架",
      publisherId: "2",
      publisherName: "2-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 23:48:32",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691114591361294337",
          contentId: "1691114590576959490",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "aa97277ba1554f25a90136e9015684c0",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691110816542220289",
      title: "2H5",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 23:33:33",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 1,
      contentTypeTxt: "H5链接",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: "http://www.baidu.com",
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl:
        "http://test-portal-obs.goktech.cn/174908214fa449fea0bc706e55c54deb.jpeg?x-image-process=style/148_104",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1691102407411490818",
      title: "1图文",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 23:00:08",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>11</p>",
      weight: 0,
      remarks: "",
      coverImageUrl:
        "http://test-portal-obs.goktech.cn/06ee7805611749cfb546214688d26390.png?x-image-process=style/148_104",
      showFlag: 0,
      fileList: [
        {
          id: "1691110625596530690",
          contentId: "1691102407411490818",
          fileType: 1,
          fileTypeTxt: "文件",
          fileId: "1691110603928756225",
          fileSize: "22229",
          videoKey: null,
          videoProgress: null,
          createBy: null,
          createTime: null,
          original: "前端测试试题.md",
          fileUrl:
            "/portal/sys-file/test-portal/68f2d763b7f843f5bad0ff68609c6be9.md",
          fileName: "68f2d763b7f843f5bad0ff68609c6be9.md",
        },
        {
          id: "1691110625596530691",
          contentId: "1691102407411490818",
          fileType: 1,
          fileTypeTxt: "文件",
          fileId: "1691110606470504450",
          fileSize: "987975",
          videoKey: null,
          videoProgress: null,
          createBy: null,
          createTime: null,
          original: "能力域.jpeg",
          fileUrl:
            "/portal/sys-file/test-portal/300ee177eb5b40e39f4d12aee169d182.jpeg",
          fileName: "300ee177eb5b40e39f4d12aee169d182.jpeg",
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691019427925340161",
      title: "6666==",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 17:30:24",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691019429292683266",
          contentId: "1691019427925340161",
          fileType: 2,
          fileTypeTxt: "视频",
          fileId: null,
          fileSize: null,
          videoKey: "09122c181b22c25ce5608e76a6056f6f",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691018275041959937",
      title: "有视频的新闻资讯",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 17:25:49",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691018275901792258",
          contentId: "1691018275041959937",
          fileType: 1,
          fileTypeTxt: "文件",
          fileId: null,
          fileSize: null,
          videoKey: "c045c021a0d10d538b14a405ee832297",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1691017668247805954",
      title: "5555",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 17:23:24",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [
        {
          id: "1691017669191524353",
          contentId: "1691017668247805954",
          fileType: 1,
          fileTypeTxt: "文件",
          fileId: null,
          fileSize: null,
          videoKey: "f14263559086568ac2dcb9b0024f99d3",
          videoProgress: 0,
          createBy: null,
          createTime: null,
          original: null,
          fileUrl: null,
          fileName: null,
        },
      ],
      relationShowFlag: 1,
    },
    {
      id: "1690998783971528705",
      title: "1111111",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 16:08:22",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690998566379425793",
      title: "123123234234",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 16:07:30",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>是的发送发送到发</p>",
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690993379526258690",
      title: "2323",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 15:46:53",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690993260210892802",
      title: "2323",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 15:46:25",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690992969952473089",
      title: "222333",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 15:45:16",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>2233</p>",
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690992743086764034",
      title: "11112222",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "1-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-14 15:44:22",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 2,
      contentTypeTxt: "视频",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: null,
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1690747879286706177",
      title: "2",
      status: 0,
      statusTxt: "上架",
      publisherId: "2",
      publisherName: "2-一级部门",
      publishTime: null,
      createBy: "admin",
      createTime: "2023-08-13 23:31:22",
      businessType: 2,
      businessTypeTxt: "公司新闻",
      contentType: 1,
      contentTypeTxt: "H5链接",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: "2",
      relationContentId: "0",
      contentText: "<p><br></p>",
      weight: 0,
      remarks: "",
      coverImageUrl:
        "http://test-portal-obs.goktech.cn/4eb4649fb36349a7813bf46159a971a8.jpeg?x-image-process=style/148_104",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1688842781029744641",
      title: "新闻资讯test6",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "发布者测试6",
      publishTime: "2023-08-08 15:00:00",
      createBy: "admin",
      createTime: "2023-08-08 17:21:11",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "正文修改测试6",
      weight: 0,
      remarks: "",
      coverImageUrl: "",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1688828294408904706",
      title: "行业资讯行业资讯行业资讯图文",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "选项一",
      publishTime: "2023-08-08 00:00:00",
      createBy: "admin",
      createTime: "2023-08-08 16:23:37",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 0,
      contentTypeTxt: "图文",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: null,
      relationContentId: "0",
      contentText: "<p>行业资讯行业资讯行业资讯</p>",
      weight: 0,
      remarks: "",
      coverImageUrl: "",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
    {
      id: "1688828070743449602",
      title: "141414",
      status: 0,
      statusTxt: "上架",
      publisherId: "1",
      publisherName: "选项一",
      publishTime: "2023-08-08 00:00:00",
      createBy: "admin",
      createTime: "2023-08-08 16:22:44",
      businessType: 3,
      businessTypeTxt: "行业资讯",
      contentType: 1,
      contentTypeTxt: "H5链接",
      contentCategory: 4,
      contentCategoryTxt: "新闻资讯",
      linkAddress: "https://baidu.com",
      relationContentId: "0",
      contentText: null,
      weight: 0,
      remarks: "",
      coverImageUrl: "",
      showFlag: 0,
      fileList: [],
      relationShowFlag: 1,
    },
  ],
  total: 34,
  size: 30,
  current: 1,
  orders: [],
  optimizeCountSql: true,
  searchCount: true,
  maxLimit: null,
  countId: null,
  pages: 2,
};
export default res;
